# -*- coding: utf-8 -*-
"""Figures for the bias law and for learner 2."""
from __future__ import annotations

from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np

from .bias import sweep as bias_sweep
from .experiment2 import CONDITION_META, TAU_TRUE

plt.rcParams.update({"font.size": 8, "axes.spines.top": False, "axes.spines.right": False})


def _save(fig, path: Path) -> None:
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(path.with_suffix(".png"), dpi=220, bbox_inches="tight")
    fig.savefig(path.with_suffix(".pdf"), bbox_inches="tight")
    plt.close(fig)


def plot_bias_law(rows, path) -> None:
    """Co-contraction divides the misspecification bias by rho(xi)."""
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(7.2, 2.7))
    xi = np.array([r["xi"] for r in rows])
    fitted = np.array([r["bias_fitted"] for r in rows])
    pred = np.array([r["bias_predicted"] for r in rows])

    ax1.semilogy(xi, np.abs(fitted), "o-", color="#8C1428", lw=1.3, label="least squares fit")
    ax1.semilogy(xi, pred, "s--", color="#1B365D", lw=1.3,
                 label=r"$(\tau_1+\tau_2)/\rho(\xi)$")
    ax1.set_xlabel(r"co-contraction $\xi$")
    ax1.set_ylabel(r"bias in $\hat\tau_d$  (s)")
    ax1.legend(frameon=False, fontsize=6.5)
    ax1.set_title("a reduced-order learner is biased,\nand stiffening divides the bias by "
                  r"$\rho$", fontsize=7)

    ax2.plot(xi, [r["tau_hat_fitted"] for r in rows], "o-", color="#8C1428", lw=1.3)
    ax2.axhline(TAU_TRUE[0], color="k", ls=":", lw=0.9)
    ax2.axhline(sum(TAU_TRUE), color="grey", ls="--", lw=0.9)
    ax2.text(xi[-1], sum(TAU_TRUE), r"  $\tau_d+\tau_1+\tau_2$", va="center", fontsize=6.5)
    ax2.text(xi[-1], TAU_TRUE[0], r"  true $\tau_d$", va="center", fontsize=6.5)
    ax2.set_xlabel(r"co-contraction $\xi$")
    ax2.set_ylabel(r"fitted $\hat\tau_d$  (s)")
    ax2.set_title("three lags in a row feel like one lag\nequal to their sum", fontsize=7)
    _save(fig, path)


def plot_learner2(logs, path) -> None:
    fig, (ax1, ax2, ax3) = plt.subplots(1, 3, figsize=(9.6, 2.7))
    n = logs[next(iter(logs))][0].err.size
    t = np.arange(1, n + 1)

    for c in logs:
        meta = CONDITION_META[c]
        neff = np.mean(np.stack([lg.n_eff for lg in logs[c]]), axis=0)
        ax1.plot(t, neff, color=meta["color"], lw=1.3, label=meta["label"])
    ax1.axhline(3.0, color="k", ls=":", lw=0.8)
    ax1.set_xlabel("trial")
    ax1.set_ylabel(r"effective order $n_{\mathrm{eff}}$")
    ax1.legend(frameon=False, fontsize=6)
    ax1.set_title("order recruitment is emergent,\nnot scheduled", fontsize=7)

    for c in logs:
        meta = CONDITION_META[c]
        b = np.mean(np.stack([np.abs(lg.bias_d) for lg in logs[c]]), axis=0)
        ax2.semilogy(t, b, color=meta["color"], lw=1.3)
    ax2.set_xlabel("trial")
    ax2.set_ylabel(r"$|\hat\tau_d - \tau_d|$  (s)")
    ax2.set_title("the deep end passes through a badly\nbiased belief about the slow mode",
                  fontsize=7)

    order = list(logs)
    peak = [np.median([np.max(np.abs(lg.bias_d[1:])) for lg in logs[c]]) for c in order]
    fails = [np.mean([lg.n_failed for lg in logs[c]]) for c in order]
    x = np.arange(len(order))
    ax3.bar(x - 0.2, peak, width=0.38, color=[CONDITION_META[c]["color"] for c in order],
            alpha=0.9, label="peak bias (s)")
    ax3b = ax3.twinx()
    ax3b.bar(x + 0.2, fails, width=0.38, color="grey", alpha=0.55, label="failed trials")
    ax3b.spines["top"].set_visible(False)
    ax3.set_xticks(x)
    ax3.set_xticklabels(order)
    ax3.set_ylabel("peak bias in " + r"$\hat\tau_d$ (s)")
    ax3b.set_ylabel("failed trials")
    ax3.set_title("what separates the schedules is risk,\nnot trial count", fontsize=7)
    _save(fig, path)


def write_snippet(rows, logs, summary, path) -> None:
    soft = rows[0]
    stiff = [r for r in rows if r["xi"] >= 3.0][0]
    lines = [
        "% auto-generated by scripts/run_learner2.py -- do not edit by hand",
        f"A learner restricted to fewer modes than the object has is biased by the "
        f"time constants it omits: expanding the plant at low frequency gives "
        f"$\\hat\\tau = \\tau_d + (\\tau_1+\\tau_2)/\\rho(\\xi)$. Co-contraction divides that "
        f"bias by $\\rho$, and a least squares fit confirms it, "
        f"{soft['bias_fitted']:.3f}\\,s of bias at $\\xi={soft['xi']:.1f}$ falling to "
        f"{stiff['bias_fitted']:.4f}\\,s at $\\xi={stiff['xi']:.1f}$. "
        f"Run with a two-timescale Kalman learner carrying an ARD prior over mode "
        f"participation, the effective order is no longer imposed: staying stiff prunes "
        f"the model to $n_{{\\mathrm{{eff}}}}={summary['neff_final']['K3']:.2f}$ with an "
        f"unbiased dominant estimate, while confidence-gated relaxation holds "
        f"$n_{{\\mathrm{{eff}}}}$ at one and then recruits to "
        f"{summary['neff_final']['K2']:.2f} at the moment co-contraction falls. "
        f"The deep end reaches the same asymptote but swings through a peak dominant-mode "
        f"error of {summary['peak_bias']['K1']:.2f}\\,s against "
        f"{summary['peak_bias']['K2']:.2f}\\,s for the staged learner, and fails "
        f"{summary['n_failed']['K1']:.1f} trials against "
        f"{summary['n_failed']['K2']:.1f}.",
    ]
    Path(path).write_text("\n".join(lines) + "\n")
