# -*- coding: utf-8 -*-
"""Figures. Two of them, and the second is the one that matters."""
from __future__ import annotations

from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np

from .diagnose import curvature_spectrum, sweep
from .experiment import CONDITION_META, CRITERION

plt.rcParams.update({"font.size": 8, "axes.spines.top": False, "axes.spines.right": False})


def _save(fig, path: Path) -> None:
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(path.with_suffix(".png"), dpi=220, bbox_inches="tight")
    fig.savefig(path.with_suffix(".pdf"), bbox_inches="tight")
    plt.close(fig)


def plot_proposal_figure(logs, summary, path) -> None:
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(7.2, 2.7))
    n = summary["n_trials"]
    t = np.arange(1, n + 1)
    for c in logs:
        m = np.array(summary["mean_curve"][c])
        se = np.array(summary["se_curve"][c])
        meta = CONDITION_META[c]
        ax1.plot(t, m, color=meta["color"], lw=1.3, label=meta["label"])
        ax1.fill_between(t, m - se, m + se, color=meta["color"], alpha=0.18, lw=0)
    ax1.axhline(CRITERION, color="k", ls=":", lw=0.8)
    ax1.set_yscale("log")
    ax1.set_xlabel("trial")
    ax1.set_ylabel("model error (relative impulse)")
    ax1.legend(frameon=False, fontsize=6.5)

    order = list(logs)
    med = [summary["ttc_median"][c] for c in order]
    ax2.bar(
        range(len(order)),
        med,
        color=[CONDITION_META[c]["color"] for c in order],
        alpha=0.85,
    )
    for i, c in enumerate(order):
        vals = np.array([lg.ttc for lg in logs[c]], dtype=float)
        ax2.plot(np.full(vals.size, i) + np.random.uniform(-0.13, 0.13, vals.size),
                 vals, "o", ms=2, color="k", alpha=0.4)
    ax2.axhline(n + 1, color="k", ls=":", lw=0.8)
    ax2.set_xticks(range(len(order)))
    ax2.set_xticklabels(order)
    ax2.set_ylabel("trials to criterion")
    ax2.set_title("dotted line = never reached", fontsize=7)
    _save(fig, path)


def plot_mechanism(logs, summary, path) -> None:
    """Why the sample-complexity route to the hypothesis is closed."""
    fig, axes = plt.subplots(1, 3, figsize=(9.6, 2.7))
    ax1, ax2, ax3 = axes

    rows = sweep()
    ax1.semilogy([d["xi"] for d in rows], [d["kappa"] for d in rows], "o-", color="#1B365D", lw=1.3)
    ax1.set_xlabel(r"co-contraction $\xi$")
    ax1.set_ylabel(r"$\kappa(\Phi)$ of the full third-order fit")
    ax1.set_title("stiffening destroys, not improves,\nidentifiability of the transients", fontsize=7)

    soft = curvature_spectrum(0.7, 0.25)
    stiff = curvature_spectrum(3.0, 0.80)
    for d, mk, lab, col in ((soft, "o", r"soft, fast ($\xi=0.7$)", "#8C1428"),
                            (stiff, "s", r"stiff, slow ($\xi=3$)", "#1B365D")):
        ax2.loglog(d["curvature"], d["behaviour_cost"], mk, color=col, ms=6, label=lab)
    ax2.set_xlabel(r"curvature $\lambda_i$  (how fast it is learned)")
    ax2.set_ylabel("behavioural cost of\ngetting this direction wrong")
    ax2.legend(frameon=False, fontsize=6.5)
    ax2.set_title("badly identified directions are\nalso behaviourally cheap", fontsize=7)

    n = summary["n_trials"]
    t = np.arange(1, n + 1)
    for c in logs:
        ax3.plot(t, summary["fail_curve"][c], color=CONDITION_META[c]["color"],
                 lw=1.3, label=CONDITION_META[c]["label"])
    ax3.set_xlabel("trial")
    ax3.set_ylabel("cumulative failed trials")
    ax3.legend(frameon=False, fontsize=6.5)
    ax3.set_title("co-contraction does buy safety", fontsize=7)
    _save(fig, path)


def write_snippet(summary, path) -> None:
    t = {x["contrast"]: x for x in summary["tests"]}
    s1 = t["S2 vs S1"]
    lines = [
        "% auto-generated by scripts/run_curriculum.py -- do not edit by hand",
        f"Across {summary['n_seeds']['S2']} seeds the order-recruitment schedule (S2) reached "
        f"criterion in a median of {summary['ttc_median']['S2']:.0f} trials against "
        f"{summary['ttc_median']['S1']:.0f} for the deep end (S1), "
        f"{s1['direction']} ($p_{{\\mathrm{{Holm}}}}={s1['p_holm']:.3g}$, {s1['stars']}). "
        f"Staying stiff (S3) never reached criterion, plateauing at a model error of "
        f"{summary['asymp_err']['S3']:.2f} because the compressed transients are never "
        f"re-exposed. Co-contraction did reduce failed trials, from "
        f"{summary['n_failed']['S1']:.1f} in S1 to {summary['n_failed']['S2']:.1f} in S2, "
        "but it did not reduce the number of trials needed to identify the object. "
        "The reason is visible in the curvature spectrum: the parameter directions that "
        "are worst conditioned are also the ones whose misestimation costs least "
        "behaviourally, so the sample-complexity advantage of order reduction does not "
        "translate into a behavioural advantage.",
    ]
    Path(path).write_text("\n".join(lines) + "\n")
