# -*- coding: utf-8 -*-
"""Figures for the slosh bias law and Learner 3."""
from __future__ import annotations

from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np

from .experiment3 import CONDITION_META
from .slosh import TAU_D, WN, predicted_tau_hat

plt.rcParams.update({"font.size": 8, "axes.spines.top": False, "axes.spines.right": False})


def _save(fig, path: Path) -> None:
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(path.with_suffix(".png"), dpi=220, bbox_inches="tight")
    fig.savefig(path.with_suffix(".pdf"), bbox_inches="tight")
    plt.close(fig)


def plot_bias_law(rows, path) -> None:
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(7.2, 2.7))
    xi = np.array([r["xi"] for r in rows])
    fitted = np.array([r["bias_fitted"] for r in rows])
    pred = np.array([r["bias_predicted"] for r in rows])

    ax1.semilogy(xi, np.abs(fitted), "o-", color="#8C1428", lw=1.3, label="least squares fit")
    ax1.semilogy(xi, pred, "s--", color="#1B365D", lw=1.3,
                 label=r"$2\zeta/(\omega_n\rho(\xi))$")
    ax1.set_xlabel(r"co-contraction $\xi$")
    ax1.set_ylabel(r"bias in $\hat\tau_d$  (s)")
    ax1.legend(frameon=False, fontsize=6.5)
    ax1.set_title("a first-order fit to a sloshing cup is biased\n"
                  r"by $2\zeta/\omega_n$; stiffening divides that by $\rho$", fontsize=7)

    ax2.plot(xi, [r["tau_hat_fitted"] for r in rows], "o-", color="#8C1428", lw=1.3)
    ax2.axhline(TAU_D, color="k", ls=":", lw=0.9)
    ax2.axhline(predicted_tau_hat(0.7), color="grey", ls="--", lw=0.9)
    ax2.text(xi[-1], predicted_tau_hat(0.7), r"  $\tau_d+2\zeta/\omega_n$", va="center", fontsize=6.5)
    ax2.text(xi[-1], TAU_D, r"  true $\tau_d$", va="center", fontsize=6.5)
    ax2.set_xlabel(r"co-contraction $\xi$")
    ax2.set_ylabel(r"fitted $\hat\tau_d$  (s)")
    ax2.set_title("same bias law, now for a complex-pole slosh", fontsize=7)
    _save(fig, path)


def plot_learner3(logs, path) -> None:
    fig, axes = plt.subplots(1, 3, figsize=(9.6, 2.7))
    ax1, ax2, ax3 = axes
    n = logs[next(iter(logs))][0].err.size
    t = np.arange(1, n + 1)

    for c in logs:
        meta = CONDITION_META[c]
        neff = np.mean(np.stack([lg.n_eff for lg in logs[c]]), axis=0)
        ax1.plot(t, neff, color=meta["color"], lw=1.3, label=meta["label"])
    ax1.axhline(2.0, color="k", ls=":", lw=0.8)
    ax1.set_xlabel("trial")
    ax1.set_ylabel(r"effective order $n_{\mathrm{eff}}$")
    ax1.legend(frameon=False, fontsize=5.5)
    ax1.set_title("slosh weight is recruited from data,\nnot scheduled", fontsize=7)

    for c in logs:
        meta = CONDITION_META[c]
        dw = np.mean(np.stack([np.abs(lg.wn_hat - WN) for lg in logs[c]]), axis=0)
        ax2.semilogy(t, np.maximum(dw, 1e-3), color=meta["color"], lw=1.3)
    ax2.axhline(abs(4.0 - WN), color="grey", ls=":", lw=0.8)
    ax2.set_xlabel("trial")
    ax2.set_ylabel(r"$|\hat\omega_n - \omega_n|$  (rad/s)")
    ax2.set_title("deep-end frequency error starts at\none octave and has to climb out", fontsize=7)

    order = list(logs)
    peak = [np.median([np.max(np.abs(lg.bias_d[1:])) for lg in logs[c]]) for c in order]
    fails = [np.mean([lg.n_failed for lg in logs[c]]) for c in order]
    x = np.arange(len(order))
    ax3.bar(x - 0.2, peak, width=0.38, color=[CONDITION_META[c]["color"] for c in order],
            alpha=0.9, label="peak bias (s)")
    ax3b = ax3.twinx()
    ax3b.bar(x + 0.2, fails, width=0.38, color="grey", alpha=0.55, label="failed trials")
    ax3b.spines["top"].set_visible(False)
    ax3.set_xticks(x)
    ax3.set_xticklabels(order)
    ax3.set_ylabel("peak bias in " + r"$\hat\tau_d$ (s)")
    ax3b.set_ylabel("failed trials")
    ax3.set_title("identification metrics only:\nno task score", fontsize=7)
    _save(fig, path)


def write_snippet(rows, logs, summary, path) -> None:
    soft = rows[0]
    stiff = [r for r in rows if r["xi"] >= 3.0][0]
    lines = [
        "% auto-generated by scripts/run_learner3.py -- do not edit by hand",
        f"Replacing the two real transients with a lightly damped slosh "
        f"$\\omega_n={WN:.0f}$ rad/s, $\\zeta=0.12$ leaves the bias law intact: "
        f"a first-order fit inherits $\\hat\\tau = \\tau_d + 2\\zeta/(\\omega_n\\rho(\\xi))$, "
        f"{soft['bias_fitted']:.3f}\\,s of bias at $\\xi={soft['xi']:.1f}$ falling to "
        f"{stiff['bias_fitted']:.4f}\\,s at $\\xi={stiff['xi']:.1f}$. "
        f"A two-timescale EKF that carries a participation weight on the resonance "
        f"starts one octave wrong on $\\omega_n$. Open-loop deep end (C1) median "
        f"trials-to-criterion {summary['ttc_median']['C1']:.0f} against "
        f"{summary['ttc_median']['C2']:.0f} for the open curriculum; closed-loop "
        f"plant inversion (C4) {summary['ttc_median']['C4']:.0f} against "
        f"{summary['ttc_median']['C5']:.0f} for the closed curriculum. "
        f"Peak dominant-mode bias {summary['peak_bias']['C1']:.3f}\\,s (C1) vs "
        f"{summary['peak_bias']['C2']:.3f}\\,s (C2); failed trials "
        f"{summary['n_failed']['C1']:.1f} vs {summary['n_failed']['C2']:.1f}. "
        f"Scoring is object impulse error only; tracking is logged and unused.",
    ]
    Path(path).write_text("\n".join(lines) + "\n")
